
package project4;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class View extends javax.swing.JFrame {

    
    public View() {
        initComponents();
        
        //Center
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) / 2);
        int y = (int) ((screen.getHeight() - getHeight()) / 2);
        setLocation(x, y);
       
    }
    //Search Panel 
    public String getSearch(){
        return SearchField.getText();
    }
    
    public void setSearchName(String name){
        SearchNameField.setText(name);
    }
    public void setSearchType(String type){
        SearchTypeField.setText(type);
    }
    public void setSearchLocation(String location){
        SearchLocationField.setText(location);
    }
    public void addSearchAnimalActionListener(ActionListener a) {
        SearchBtn.addActionListener(a);
    }
    
    
    //Add Animal Panel
    public String getAddName() {
        return AddNameField.getText();
    }
    public void setAddName(String name) {
        AddNameField.setText(name);
    }
    public String getAddType() {
        return AddTypeField.getText();
    }
    public void setAddType(String type) {
        AddTypeField.setText(type);
    }
    public String getAddLocation(){
        return AddLocationField.getText();
    }
    public void setAddLocation(String location) {
        AddLocationField.setText(location);
    }
    public void addAddAnimalActionListener(ActionListener a) {
        addAnimalBtn.addActionListener(a);
    }
    public void addReset1ActionListener(ActionListener a) {
        Reset1.addActionListener(a);
    }
    
    //Add Activity
    public String getActivityName() {
        return NameField.getText();
    }
    public void setActivityName(String name) {
        NameField.setText(name);
    }
    public String getAddActivity() {
        return ActivityField.getText();
    }
    public void setActivity(String activity) {
        ActivityField.setText(activity);
    }
    public void addActivityActionListener(ActionListener a) {
        AddActivityBtn.addActionListener(a);
    }
    public void addReset2ActionListener(ActionListener a) {
        Reset2.addActionListener(a);
    }
    
    //Transport
    public String getMoveName(){
        return MoveInNameField.getText();
    }
    public void setMoveName(String s){
        MoveInNameField.setText(s);
    }
   
    public String getMoveLocation(){
        return MoveInField.getText();
    }
    public void setMoveLocation(String in) {
        MoveInField.setText(in);
    }
    
    public String getMoveOutName(){
        return MoveOutNameField.getText();
    }
    public void setMoveOutName(String s){
        MoveOutNameField.setText(s);
    }
    public String getMoveOutType(){
        return MoveOutTypeField.getText();
    }
    public void setMoveOutType(String s){
        MoveOutTypeField.setText(s);
    }    
    
    public void addMoveInListener(ActionListener a) {
        MoveInBtn.addActionListener(a);
    }
    public void addMoveOutListener(ActionListener a) {
        MoveOutBtn.addActionListener(a);
    }
    public void addReset3ActionListener(ActionListener a) {
        Reset3.addActionListener(a);
    }
    
    //Activity Log
  
    public void setActivityTableModel(TableModel model) {
        ActivityLog.setModel(model);
    }
    
    public void setActivityLogValue (String s, int row, int column){
        ActivityLog.setValueAt((Object)s, row, column);
    }
    public void addActivityLog (String str1, String str2, String str3){
        DefaultTableModel table = (DefaultTableModel) ActivityLog.getModel();
        table.addRow(new Object[]{str1,str2,str3});
    }
    
    //Location Log
   
    public void setLocationTableModel(TableModel model) {
        LocationLog.setModel(model);
    }
    
    public void setLocationLogValue (String s, int row, int column){
        LocationLog.setValueAt((Object)s, row, column);
    }    
    public void addLocationLogValue (String str1, String str2, String str3){
        DefaultTableModel table = (DefaultTableModel) LocationLog.getModel();
        table.addRow(new Object[]{str1,str2,str3});
    }
    
    
    //Menu Item: Exit
    public void addExitActionListener(ActionListener a) {
        Exit.addActionListener(a);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        ContentPane = new javax.swing.JTabbedPane();
        SearchPane = new javax.swing.JPanel();
        SearchName = new javax.swing.JLabel();
        SearchNameField = new javax.swing.JTextField();
        SearchType = new javax.swing.JLabel();
        SearchTypeField = new javax.swing.JTextField();
        SearchName2 = new javax.swing.JLabel();
        SearchLocationField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddAnimalPane = new javax.swing.JPanel();
        addNameTitle = new javax.swing.JLabel();
        addTypeTitle = new javax.swing.JLabel();
        AddNameField = new javax.swing.JTextField();
        AddLocationField = new javax.swing.JTextField();
        addLocationTitle = new javax.swing.JLabel();
        AddTypeField = new javax.swing.JTextField();
        Reset1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LocationLog = new javax.swing.JTable();
        addAnimalBtn = new javax.swing.JButton();
        AddActivityPane = new javax.swing.JPanel();
        AnimalNameTitle = new javax.swing.JLabel();
        AddActivityTitle = new java.awt.Label();
        ActivityField = new javax.swing.JTextField();
        AddActivityBtn = new javax.swing.JButton();
        Reset2 = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ActivityLog = new javax.swing.JTable();
        TransportPane = new javax.swing.JPanel();
        CategoryIn = new javax.swing.JLabel();
        CateoryOut = new javax.swing.JLabel();
        MoveInTitle = new javax.swing.JLabel();
        MoveInField = new javax.swing.JTextField();
        MoveOutBtn = new javax.swing.JButton();
        MoveInBtn = new javax.swing.JButton();
        Reset3 = new javax.swing.JButton();
        MoveOutTitle1 = new javax.swing.JLabel();
        MoveOutTypeTitle = new javax.swing.JLabel();
        MoveOutNameField = new javax.swing.JTextField();
        MoveOutTypeField = new javax.swing.JTextField();
        MoveInNameTitle = new javax.swing.JLabel();
        MoveInNameField = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SearchPane.setBackground(new java.awt.Color(204, 204, 255));
        SearchPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchName.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        SearchName.setText("Name:");
        SearchPane.add(SearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        SearchNameField.setEditable(false);
        SearchPane.add(SearchNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 178, -1));

        SearchType.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        SearchType.setText("Type:");
        SearchPane.add(SearchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 139, -1, -1));

        SearchTypeField.setEditable(false);
        SearchPane.add(SearchTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 178, -1));

        SearchName2.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        SearchName2.setText("Location:");
        SearchPane.add(SearchName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 216, -1, -1));

        SearchLocationField.setEditable(false);
        SearchPane.add(SearchLocationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 178, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH FOR ANIMAL:");
        SearchPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        SearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchPane.add(SearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, -1));

        SearchBtn.setText("SEARCH");
        SearchPane.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel2.setText("Animal's Name");
        SearchPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        ContentPane.addTab("Search", SearchPane);

        AddAnimalPane.setBackground(new java.awt.Color(204, 255, 204));
        AddAnimalPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNameTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        addNameTitle.setText("Name:");
        AddAnimalPane.add(addNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        addTypeTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        addTypeTitle.setText("Type:");
        AddAnimalPane.add(addTypeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        AddAnimalPane.add(AddNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 197, -1));
        AddAnimalPane.add(AddLocationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 197, -1));

        addLocationTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        addLocationTitle.setText("Location:");
        AddAnimalPane.add(addLocationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        AddAnimalPane.add(AddTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 197, -1));

        Reset1.setText("Reset");
        AddAnimalPane.add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        LocationLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal's Name", "Animal's Type", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LocationLog);

        AddAnimalPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, 550, 390));

        addAnimalBtn.setText("Add Animal");
        AddAnimalPane.add(addAnimalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        ContentPane.addTab("Add Animal", AddAnimalPane);

        AddActivityPane.setBackground(new java.awt.Color(255, 153, 153));
        AddActivityPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnimalNameTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        AnimalNameTitle.setText("Name:");
        AddActivityPane.add(AnimalNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        AddActivityTitle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        AddActivityTitle.setText("Activity:");
        AddActivityPane.add(AddActivityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        AddActivityPane.add(ActivityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, -1));

        AddActivityBtn.setText("Add Activity");
        AddActivityPane.add(AddActivityBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        Reset2.setText("Reset");
        AddActivityPane.add(Reset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 30));
        AddActivityPane.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, -1));

        ActivityLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal's Name", "Activity", "Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ActivityLog);

        AddActivityPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 0, 500, 390));

        ContentPane.addTab("Add Activity", AddActivityPane);

        TransportPane.setBackground(new java.awt.Color(153, 204, 255));
        TransportPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryIn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        CategoryIn.setText("Within Zoo");
        TransportPane.add(CategoryIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 73, -1, -1));

        CateoryOut.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        CateoryOut.setText("Outside of the Zoo");
        TransportPane.add(CateoryOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        MoveInTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        MoveInTitle.setText("Move to: ");
        MoveInTitle.setToolTipText("");
        TransportPane.add(MoveInTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        TransportPane.add(MoveInField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 222, -1));

        MoveOutBtn.setText("Move Out");
        TransportPane.add(MoveOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        MoveInBtn.setText("Move Around the Zoo");
        TransportPane.add(MoveInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        Reset3.setText("Reset");
        TransportPane.add(Reset3, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 262, -1, -1));

        MoveOutTitle1.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        MoveOutTitle1.setText("Name:");
        MoveOutTitle1.setToolTipText("");
        TransportPane.add(MoveOutTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 114, -1, -1));

        MoveOutTypeTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        MoveOutTypeTitle.setText("Type:");
        MoveOutTypeTitle.setToolTipText("");
        TransportPane.add(MoveOutTypeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));
        TransportPane.add(MoveOutNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 222, -1));
        TransportPane.add(MoveOutTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 222, -1));

        MoveInNameTitle.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        MoveInNameTitle.setText("Name:");
        MoveInNameTitle.setToolTipText("");
        TransportPane.add(MoveInNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        TransportPane.add(MoveInNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 222, -1));

        ContentPane.addTab("Transporting", TransportPane);

        Title.setFont(new java.awt.Font("Superclarendon", 3, 36)); // NOI18N
        Title.setText("Logistics");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project4/zooLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPane)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        File.setText("File");

        Exit.setText("Exit");
        File.add(Exit);

        MenuBar.add(File);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActivityField;
    private javax.swing.JTable ActivityLog;
    private javax.swing.JButton AddActivityBtn;
    private javax.swing.JPanel AddActivityPane;
    private java.awt.Label AddActivityTitle;
    private javax.swing.JPanel AddAnimalPane;
    private javax.swing.JTextField AddLocationField;
    private javax.swing.JTextField AddNameField;
    private javax.swing.JTextField AddTypeField;
    private javax.swing.JLabel AnimalNameTitle;
    private javax.swing.JLabel CategoryIn;
    private javax.swing.JLabel CateoryOut;
    private javax.swing.JTabbedPane ContentPane;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu File;
    private javax.swing.JTable LocationLog;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton MoveInBtn;
    private javax.swing.JTextField MoveInField;
    private javax.swing.JTextField MoveInNameField;
    private javax.swing.JLabel MoveInNameTitle;
    private javax.swing.JLabel MoveInTitle;
    private javax.swing.JButton MoveOutBtn;
    private javax.swing.JTextField MoveOutNameField;
    private javax.swing.JLabel MoveOutTitle1;
    private javax.swing.JTextField MoveOutTypeField;
    private javax.swing.JLabel MoveOutTypeTitle;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Reset2;
    private javax.swing.JButton Reset3;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField SearchLocationField;
    private javax.swing.JLabel SearchName;
    private javax.swing.JLabel SearchName2;
    private javax.swing.JTextField SearchNameField;
    private javax.swing.JPanel SearchPane;
    private javax.swing.JLabel SearchType;
    private javax.swing.JTextField SearchTypeField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TransportPane;
    private javax.swing.JButton addAnimalBtn;
    private javax.swing.JLabel addLocationTitle;
    private javax.swing.JLabel addNameTitle;
    private javax.swing.JLabel addTypeTitle;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
